name: Run Tests

on:
  push:
    paths:
      - dictum/**
      - .github/**
  workflow_dispatch:

jobs:
  test:
    name: Run Dictum tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dictum
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-dictum
      - run: poetry run pytest
      - uses: codecov/codecov-action@v3
        with:
          files: dictum/coverage.xml
  test-backend-postgres:
    name: Run tests for Postgres backend
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-backend
        with:
          backend: postgres
